/* Generated by scripts/build-content.ts. Do not edit by hand. */
export const characters = [
  {
    "id": "underground-man",
    "canonicalName": "Underground Man",
    "aliases": [
      "Underground Man",
      "the underground man",
      "the narrator"
    ],
    "workIds": [
      "notes-from-underground"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He wants a truth no illusion can survive, then uses that truth to excuse withdrawal from life.",
    "gift": "He can detect self-deception before it hardens into virtue.",
    "danger": "His danger is turning lucidity into a private room where no one can reach him.",
    "notToRomanticize": "Wounded intelligence is not courage when it refuses contact."
  },
  {
    "id": "raskolnikov",
    "canonicalName": "Rodion Raskolnikov",
    "aliases": [
      "Rodion Raskolnikov",
      "Raskolnikov",
      "Rodion Romanovich",
      "Rodion Romanovitch"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He wants to stand above ordinary morality, but his conscience keeps returning him to the human face.",
    "gift": "He can follow an idea to its moral consequence once suffering makes it concrete.",
    "danger": "His danger is letting abstraction make other people available for sacrifice.",
    "notToRomanticize": "Brilliance does not absolve violence committed on behalf of a theory."
  },
  {
    "id": "sonya-marmeladova",
    "canonicalName": "Sonya Marmeladova",
    "aliases": [
      "Sonya Marmeladova",
      "Sonia",
      "Sonechka",
      "Sofya Semyonovna"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "exit-archetype"
    ],
    "coreContradiction": "She bears humiliation without allowing it to become contempt for the guilty.",
    "gift": "She can stay near another person's ruin without making herself its judge.",
    "danger": "Her danger is accepting too much suffering as if endurance alone were salvation.",
    "notToRomanticize": "Her mercy should not be used to beautify exploitation."
  },
  {
    "id": "svidrigailov",
    "canonicalName": "Arkady Svidrigailov",
    "aliases": [
      "Arkady Svidrigailov",
      "Svidrigailov",
      "Arkady Ivanovich",
      "Arkady Ivanovitch",
      "Svidrigaïlov"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He understands guilt clearly enough to name it, but not enough to hope it can still demand him.",
    "gift": "He sees through polite morality and its evasions.",
    "danger": "His danger is treating the soul as already spent and therefore excused.",
    "notToRomanticize": "Detachment is not depth when it has stopped expecting accountability."
  },
  {
    "id": "prince-myshkin",
    "canonicalName": "Prince Lev Myshkin",
    "aliases": [
      "Prince Myshkin",
      "Lev Myshkin",
      "Lev Nikolayevich",
      "Myshkin",
      "Prince Muishkin",
      "Muishkin"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "exit-archetype"
    ],
    "coreContradiction": "He sees the wound before the offense, but cannot always protect goodness from what recognizes and uses it.",
    "gift": "He brings unarmed mercy into rooms trained by vanity, cruelty, and fear.",
    "danger": "His danger is compassion without enough boundary to survive contact.",
    "notToRomanticize": "Innocence does not repair the world simply by entering it."
  },
  {
    "id": "nastasya-filippovna",
    "canonicalName": "Nastasya Filippovna",
    "aliases": [
      "Nastasya Filippovna",
      "Nastasia",
      "Nastasya",
      "Filippovna",
      "Nastasia Philipovna",
      "Nastasia Philipovna Barashkoff"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "She wants her innocence recognized, but refuses any rescue that secretly depends on her humiliation.",
    "gift": "She exposes salvation that wants possession, gratitude, or spectacle.",
    "danger": "Her danger is making ruin the only proof that the wound was real.",
    "notToRomanticize": "Her self-destruction is not glamour; it is injury defending itself badly."
  },
  {
    "id": "rogozhin",
    "canonicalName": "Parfyon Rogozhin",
    "aliases": [
      "Parfyon Rogozhin",
      "Rogozhin",
      "Parfyon Semyonovich",
      "Rogojin",
      "Parfen Rogojin"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He wants love to redeem him, but tries to secure it by possession.",
    "gift": "He knows passion without diluting it into acceptable speech.",
    "danger": "His danger is devotion becoming ownership and ownership becoming violence.",
    "notToRomanticize": "Intensity is not proof of love when it cannot release the beloved."
  },
  {
    "id": "ivan-karamazov",
    "canonicalName": "Ivan Karamazov",
    "aliases": [
      "Ivan Karamazov",
      "Ivan Fyodorovich",
      "Ivan Fyodorovitch",
      "Ivan"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He rejects cheap meaning because innocent suffering makes easy reconciliation morally obscene.",
    "gift": "He refuses consolation that has not passed through the fact of pain.",
    "danger": "His danger is making moral intelligence into a cell no love can enter.",
    "notToRomanticize": "Revolt can defend conscience and still starve the soul."
  },
  {
    "id": "dmitri-karamazov",
    "canonicalName": "Dmitri Karamazov",
    "aliases": [
      "Dmitri Karamazov",
      "Mitya",
      "Dmitri Fyodorovich",
      "Dmitri Fyodorovitch"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype"
    ],
    "coreContradiction": "He can repent with his whole being, but often only after passion has broken what it touched.",
    "gift": "He feels guilt, love, and truth before he has language clean enough for them.",
    "danger": "His danger is confusing emotional force with moral freedom.",
    "notToRomanticize": "Passion is not innocence, and suffering loudly is not the same as repair."
  },
  {
    "id": "alyosha-karamazov",
    "canonicalName": "Alyosha Karamazov",
    "aliases": [
      "Alyosha Karamazov",
      "Alexei Fyodorovich",
      "Alexey Fyodorovitch",
      "Alyosha"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "exit-archetype"
    ],
    "coreContradiction": "He keeps faith without lying about cruelty, shame, or collapse.",
    "gift": "He can reconcile without flattening truth into politeness.",
    "danger": "His danger is being mistaken for softness by people who cannot recognize disciplined mercy.",
    "notToRomanticize": "His compassion is active responsibility, not passive niceness."
  },
  {
    "id": "stavrogin",
    "canonicalName": "Nikolai Stavrogin",
    "aliases": [
      "Nikolai Stavrogin",
      "Stavrogin",
      "Nikolai Vsevolodovich",
      "Nikolay Vsyevolodovitch"
    ],
    "workIds": [
      "demons"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He has force, beauty, and command, but no living center willing to answer for them.",
    "gift": "He reveals how charisma behaves when it is cut loose from love, truth, and responsibility.",
    "danger": "His danger is vacancy becoming authority.",
    "notToRomanticize": "Charm without conscience is not mystery; it is danger made attractive."
  },
  {
    "id": "kirillov",
    "canonicalName": "Alexei Kirillov",
    "aliases": [
      "Alexei Kirillov",
      "Kirillov",
      "Alexey Kirillov"
    ],
    "workIds": [
      "demons"
    ],
    "tier": 1,
    "roles": [
      "primary-archetype",
      "shadow-archetype"
    ],
    "coreContradiction": "He seeks absolute freedom by surrendering his life to one fatal proof.",
    "gift": "He follows metaphysical consequences with a seriousness other people only perform.",
    "danger": "His danger is idea-possession presenting itself as liberation.",
    "notToRomanticize": "Extremity is not courage when life becomes evidence for an idea."
  },
  {
    "id": "porfiry-petrovich",
    "canonicalName": "Porfiry Petrovich",
    "aliases": [
      "Porfiry Petrovich",
      "Porfiry"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 2,
    "roles": [
      "counterforce",
      "secondary"
    ],
    "coreContradiction": "He uses pressure to draw truth out without reducing truth to procedure.",
    "gift": "He understands conscience as evidence before confession arrives.",
    "danger": "His danger is manipulation becoming its own form of pride."
  },
  {
    "id": "razumikhin",
    "canonicalName": "Razumikhin",
    "aliases": [
      "Razumikhin",
      "Dmitri Prokofych"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 2,
    "roles": [
      "exit-archetype",
      "secondary"
    ],
    "coreContradiction": "He stays practical without surrendering warmth.",
    "gift": "He brings ordinary loyalty where others perform grand theories.",
    "danger": "His danger is underestimating how deep another person's fracture runs."
  },
  {
    "id": "dunia",
    "canonicalName": "Dunia",
    "aliases": [
      "Dunia",
      "Avdotya Romanovna",
      "Dounia"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "counterforce"
    ],
    "coreContradiction": "She can sacrifice herself for family without losing the instinct for dignity.",
    "gift": "She sees coercion clearly and resists it.",
    "danger": "Her danger is accepting too much burden as proof of love."
  },
  {
    "id": "marmeladov",
    "canonicalName": "Marmeladov",
    "aliases": [
      "Marmeladov",
      "Semyon Zakharovich"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "He confesses degradation while repeating it.",
    "gift": "He can name his shame without fully hiding from it.",
    "danger": "His danger is turning confession into a substitute for change."
  },
  {
    "id": "katerina-ivanovna-crime-and-punishment",
    "canonicalName": "Katerina Ivanovna",
    "aliases": [
      "Katerina Ivanovna",
      "Katerina Ivanovna Marmeladova"
    ],
    "workIds": [
      "crime-and-punishment"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "She clings to dignity while humiliation keeps tightening around her.",
    "gift": "She refuses to let poverty erase memory or rank.",
    "danger": "Her danger is pride becoming fever."
  },
  {
    "id": "aglaya-epanchina",
    "canonicalName": "Aglaya Epanchina",
    "aliases": [
      "Aglaya Epanchina",
      "Aglaya Ivanovna",
      "Aglaya"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "counterforce"
    ],
    "coreContradiction": "She wants purity and drama while fearing the real cost of either.",
    "gift": "She can see falseness in social performance.",
    "danger": "Her danger is testing love until it breaks."
  },
  {
    "id": "lebedev",
    "canonicalName": "Lebedev",
    "aliases": [
      "Lebedev",
      "Lukyan Timofeyevich"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "He mixes religious anxiety with appetite for spectacle.",
    "gift": "He notices the hidden theatre inside public virtue.",
    "danger": "His danger is cleverness without moral steadiness."
  },
  {
    "id": "general-ivolgin",
    "canonicalName": "General Ivolgin",
    "aliases": [
      "General Ivolgin",
      "Ardalion Alexandrovich"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "He needs dignity so badly that invention becomes refuge.",
    "gift": "He exposes the hunger to be remembered as larger than one is.",
    "danger": "His danger is self-mythology replacing responsibility."
  },
  {
    "id": "ganya-ivolgin",
    "canonicalName": "Ganya Ivolgin",
    "aliases": [
      "Ganya Ivolgin",
      "Gavrila Ardalionovich",
      "Ganya"
    ],
    "workIds": [
      "the-idiot"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "shadow-archetype"
    ],
    "coreContradiction": "He wants status without admitting how much contempt it costs him.",
    "gift": "He can recognize humiliation before others name it.",
    "danger": "His danger is ambition curdling into servility."
  },
  {
    "id": "smerdyakov",
    "canonicalName": "Smerdyakov",
    "aliases": [
      "Smerdyakov",
      "Pavel Fyodorovich"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "shadow-archetype"
    ],
    "coreContradiction": "He absorbs ideas without the conscience that gave them weight.",
    "gift": "He reveals how borrowed intellect can become poison.",
    "danger": "His danger is resentment learning the language of philosophy."
  },
  {
    "id": "grushenka",
    "canonicalName": "Grushenka",
    "aliases": [
      "Grushenka",
      "Agrafena Alexandrovna"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "exit-archetype"
    ],
    "coreContradiction": "She performs hardness while still capable of mercy.",
    "gift": "She can turn scorn into tenderness when truth reaches her.",
    "danger": "Her danger is confusing revenge with freedom."
  },
  {
    "id": "katerina-ivanovna-karamazov",
    "canonicalName": "Katerina Ivanovna",
    "aliases": [
      "Katerina Ivanovna",
      "Katerina Ivanovna Verkhovtseva",
      "Katya"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "counterforce"
    ],
    "coreContradiction": "She wants moral nobility while being trapped by pride and debt.",
    "gift": "She can act from fierce responsibility.",
    "danger": "Her danger is making sacrifice into domination."
  },
  {
    "id": "father-zosima",
    "canonicalName": "Father Zosima",
    "aliases": [
      "Father Zosima",
      "Zosima",
      "Elder Zosima"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 2,
    "roles": [
      "exit-archetype",
      "counterforce"
    ],
    "coreContradiction": "He teaches universal responsibility without making it sentimental.",
    "gift": "He offers spiritual seriousness without contempt.",
    "danger": "His danger is being simplified into gentle advice."
  },
  {
    "id": "fyodor-pavlovich-karamazov",
    "canonicalName": "Fyodor Pavlovich Karamazov",
    "aliases": [
      "Fyodor Pavlovich Karamazov",
      "Fyodor Pavlovich"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "shadow-archetype"
    ],
    "coreContradiction": "He turns appetite into performance and evades shame by becoming shameless.",
    "gift": "He exposes degradation that polite life tries to hide.",
    "danger": "His danger is treating ugliness as immunity from judgment."
  },
  {
    "id": "liza-khokhlakova",
    "canonicalName": "Liza Khokhlakova",
    "aliases": [
      "Liza Khokhlakova",
      "Lise",
      "Liza"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "She wants closeness and injury at the same time.",
    "gift": "She makes hidden cruelty visible before it becomes respectable.",
    "danger": "Her danger is testing pain as proof of reality."
  },
  {
    "id": "rakitin",
    "canonicalName": "Rakitin",
    "aliases": [
      "Rakitin",
      "Mikhail Rakitin"
    ],
    "workIds": [
      "the-brothers-karamazov"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "He wants moral language without moral surrender.",
    "gift": "He detects weakness quickly.",
    "danger": "His danger is cynicism passing itself off as intelligence."
  },
  {
    "id": "shatov",
    "canonicalName": "Shatov",
    "aliases": [
      "Shatov",
      "Ivan Shatov",
      "Ivan Pavlovich"
    ],
    "workIds": [
      "demons"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "counterforce"
    ],
    "coreContradiction": "He wants belief to become flesh after surviving abstraction.",
    "gift": "He can feel the moral cost of uprooted ideas.",
    "danger": "His danger is desperation attaching itself to doctrine."
  },
  {
    "id": "pyotr-verkhovensky",
    "canonicalName": "Pyotr Verkhovensky",
    "aliases": [
      "Pyotr Verkhovensky",
      "Peter Verkhovensky",
      "Pyotr Stepanovich"
    ],
    "workIds": [
      "demons"
    ],
    "tier": 2,
    "roles": [
      "secondary",
      "shadow-archetype"
    ],
    "coreContradiction": "He speaks revolution while feeding on control.",
    "gift": "He understands how weak people can be organized by fear.",
    "danger": "His danger is ideology as appetite for domination."
  },
  {
    "id": "stepan-trofimovich",
    "canonicalName": "Stepan Trofimovich Verkhovensky",
    "aliases": [
      "Stepan Trofimovich",
      "Stepan Verkhovensky",
      "Stepan Trofimovich Verkhovensky"
    ],
    "workIds": [
      "demons"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "reference-only"
    ],
    "coreContradiction": "He loves noble ideas partly as a mirror for himself.",
    "gift": "He preserves a language of beauty and conscience.",
    "danger": "His danger is aesthetic conscience without enough action."
  },
  {
    "id": "varvara-petrovna",
    "canonicalName": "Varvara Petrovna",
    "aliases": [
      "Varvara Petrovna",
      "Varvara Stavrogina"
    ],
    "workIds": [
      "demons"
    ],
    "tier": 3,
    "roles": [
      "secondary",
      "counterforce"
    ],
    "coreContradiction": "She wants order and devotion, but often through command.",
    "gift": "She has force, intelligence, and social nerve.",
    "danger": "Her danger is care becoming ownership."
  }
] as const;

export type Character = (typeof characters)[number];
