/* Generated by scripts/build-content.ts. Do not edit by hand. */
export const dimensions = [
  "hyperconsciousness",
  "compassion",
  "resentment",
  "moralPride",
  "guilt",
  "faith",
  "revolt",
  "passion",
  "detachment",
  "selfSabotage",
  "socialDefense",
  "innocence"
] as const;

export type DimensionKey = (typeof dimensions)[number];
