import { dimensionKeys } from "../schemas/dimension.schema.js";
import { resolveProjectPath, writeTextFile } from "./fs.js";
import { loadCuratedDataSet, publishableQuotes } from "./validation.js";

function generatedArrayFile(typeName: string, exportName: string, value: unknown) {
  return [
    "/* Generated by scripts/build-content.ts. Do not edit by hand. */",
    `export const ${exportName} = ${JSON.stringify(value, null, 2)} as const;`,
    "",
    `export type ${typeName} = (typeof ${exportName})[number];`,
    ""
  ].join("\n");
}

export async function buildContent() {
  const data = await loadCuratedDataSet();
  const quotes = publishableQuotes(data.quotes);

  await writeTextFile(
    resolveProjectPath("content", "dimensions.ts"),
    [
      "/* Generated by scripts/build-content.ts. Do not edit by hand. */",
      `export const dimensions = ${JSON.stringify(dimensionKeys, null, 2)} as const;`,
      "",
      "export type DimensionKey = (typeof dimensions)[number];",
      ""
    ].join("\n")
  );

  await writeTextFile(resolveProjectPath("content", "works.ts"), generatedArrayFile("Work", "works", data.works));
  await writeTextFile(resolveProjectPath("content", "characters.ts"), generatedArrayFile("Character", "characters", data.characters));
  await writeTextFile(resolveProjectPath("content", "archetypes.ts"), generatedArrayFile("Archetype", "archetypes", data.archetypes));
  await writeTextFile(resolveProjectPath("content", "quotes.ts"), generatedArrayFile("Quote", "quotes", quotes));

  return {
    workCount: data.works.length,
    characterCount: data.characters.length,
    archetypeCount: data.archetypes.length,
    quoteCount: quotes.length
  };
}
